spring:
  application:
    name: API-GATEWAY

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaza09sfpI30AuD6697
            client-secret: yrGPTyLpHtRbYnpBAxVMCTMDn5FDmuls6_mB0e9cNI63XA_p5_5CAsVfljPjiHJQ
            scope: openid, profile, email, Internal
        provider:
          okta:
            issuer-uri: https://integrator-2454740.okta.com/oauth2/default

      resourceserver:
        jwt:
          issuer-uri: https://integrator-2454740.okta.com/oauth2/default


  #  cloud:
#    gateway:
#      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users
#
#        - id: RATING-SERVICE
#          uri: lb://RATING-SERVICE
#          predicates:
#            - Path=/ratings/**
#
#        - id: HOTEL-SERVICE
#          uri: lb://HOTEL-SERVICE
#          predicates:
#            - Path=/hotels/**

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**
            filters:
              - TokenRelay

          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/ratings/**
            filters:
              - TokenRelay

          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/hotels/**,/staffs/**
            filters:
              - TokenRelay

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        security: TRACE
        security.oauth2: TRACE
        cloud.gateway: DEBUG
        web.server: DEBUG

