spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database : microservices_ratingservice
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: RATING-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-2454740.okta.com/oauth2/default

      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: Internal
            client-id: 0oaza09sfpI30AuD6697
            client-secret: yrGPTyLpHtRbYnpBAxVMCTMDn5FDmuls6_mB0e9cNI63XA_p5_5CAsVfljPjiHJQ
        #          okta:
        #            client-id: 0oaza09sfpI30AuD6697
        #            client-secret: yrGPTyLpHtRbYnpBAxVMCTMDn5FDmuls6_mB0e9cNI63XA_p5_5CAsVfljPjiHJQ
        #            scope: openid, profile, email

        provider:
          okta:
            issuer-uri: https://integrator-2454740.okta.com/oauth2/default

server:
  port: 8083

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE